name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  
jobs:
  build:
    name: Build project
    runs-on: [windows-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.6
        
      - name: Restore Nuget
        run: nuget restore BetterCrafting.sln
      
      - name: Build Project
        run: msbuild -p:PostBuildEvent= -p:PreBuildEvent= BetterCrafting.sln
      
  
